services:
    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        develop:
            watch:
                - action: restart
                  path: ./nginx.conf

        depends_on:
            - frontend
        networks:
            - public
            - private

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /usr/src/frontend
                  ignore:
                      - node_modules/
                      - dist/

                - action: rebuild
                  path: package.json
        networks:
            - private

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /usr/src/backend

        networks:
            - private

networks:
    private:
        driver: bridge
    public:
        driver: bridge
