services:
  db:
    image: postgres:16-alpine
    container_name: school-secretary-db
    ports:
      - "1000:1000"
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - default.env
      - .env.prod
      - .env.local
    networks:
      - private
    restart: unless-stopped

  api:
    build: ./api
    image: webcorvus/school-secretary-api:latest
    container_name: school-secretary-api
    ports:
      - "8000:8000"
    volumes:
      - db_data:/api/data
    env_file:
      - default.env
      - .env.prod
      - .env.local
    depends_on:
      - db
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    develop:
      watch:
        - action: sync
          path: ./api
          target: /api
    networks:
      - private

  app:
    build: ./app
    image: webcorvus/school-secretary-app:latest
    container_name: school-secretary-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - default.env
      - .env.prod
      - .env.local
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: /app
    networks:
      - private

networks:
  private:
    driver: bridge

volumes:
  db_data:
